# k8s/user-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 4001
      targetPort: 4001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: your-dockerhub/user-service:latest
          ports:
            - containerPort: 4001
          env:
            - name: NODE_ENV
              value: "userion"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "marketplace"
            - name: POSTGRES_HOST
              value: "postgres"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
          command: ["pm2-runtime", "ecosystem.config.js", "--env", "userion"]

# Repeat above template for cart, user, user, user, user, merchant services.